name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["type: bug", "status: backlog"]
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

    - type: dropdown
      id: area
      attributes:
          label: Area
          description: Which component or service is affected?
          options:
              - Frontend (Web)
              - Mobile (iOS/Android)
              - Authentication
              - Content Management
              - Media Processing
              - Search
              - Analytics
              - Infrastructure
              - API Gateway
              - Event Streaming (Kafka)
              - Caching (Redis)
              - Observability
              - Other
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How critical is this issue?
          options:
              - P3 - Low (Minor issue, workaround available)
              - P2 - Medium (Affects functionality but not critical)
              - P1 - High (Significant impact on users)
              - P0 - Urgent (Critical system failure)
          default: 1
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Bug Description
          description: Clear and concise description of what the bug is
          placeholder: Describe the bug...
      validations:
          required: true

    - type: textarea
      id: steps
      attributes:
          label: Steps to Reproduce
          description: Steps to reproduce the behavior
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
              4. See error
      validations:
          required: true

    - type: textarea
      id: expected
      attributes:
          label: Expected Behavior
          description: What should have happened?
          placeholder: Describe expected behavior...
      validations:
          required: true

    - type: textarea
      id: actual
      attributes:
          label: Actual Behavior
          description: What actually happened?
          placeholder: Describe actual behavior...
      validations:
          required: true

    - type: textarea
      id: environment
      attributes:
          label: Environment
          description: Your environment details
          placeholder: |
              - OS: [e.g. iOS, Android, Windows, macOS]
              - Browser/App Version: [e.g. Chrome 119, iOS App 1.2.3]
              - Device: [e.g. iPhone 14, Samsung Galaxy S23]
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Add any other context, screenshots, or logs
          placeholder: Add screenshots, logs, or additional context here...
      validations:
          required: false
