name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["type: feature", "status: backlog"]
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a new feature! Please provide as much detail as possible.

    - type: dropdown
      id: area
      attributes:
          label: Area
          description: Which component or service would this feature affect?
          options:
              - Frontend (Web)
              - Mobile (iOS/Android)
              - Authentication
              - Content Management
              - Media Processing
              - Search
              - Analytics
              - Infrastructure
              - API Gateway
              - Event Streaming (Kafka)
              - Caching (Redis)
              - Observability
              - Other
      validations:
          required: true

    - type: dropdown
      id: priority
      attributes:
          label: Priority
          description: How important is this feature?
          options:
              - P3 - Low (Nice to have)
              - P2 - Medium (Would improve experience)
              - P1 - High (Important for users)
              - P0 - Urgent (Critical business need)
          default: 1
      validations:
          required: true

    - type: textarea
      id: problem
      attributes:
          label: Problem Statement
          description: What problem does this feature solve?
          placeholder: Describe the problem or pain point this feature would address...
      validations:
          required: true

    - type: textarea
      id: solution
      attributes:
          label: Proposed Solution
          description: Describe your ideal solution
          placeholder: Describe how you envision this feature working...
      validations:
          required: true

    - type: textarea
      id: alternatives
      attributes:
          label: Alternative Solutions
          description: Have you considered alternative approaches?
          placeholder: Describe any alternative solutions you've considered...
      validations:
          required: false

    - type: textarea
      id: acceptance
      attributes:
          label: Acceptance Criteria
          description: What would make this feature complete?
          placeholder: |
              - [ ] Criteria 1
              - [ ] Criteria 2
              - [ ] Criteria 3
      validations:
          required: false

    - type: textarea
      id: additional
      attributes:
          label: Additional Context
          description: Add mockups, examples, or any other context
          placeholder: Add mockups, examples, or additional context here...
      validations:
          required: false
