name: 🔒 Security Issue
description: Report a security vulnerability or concern
title: "[Security]: "
labels: ["security: vuln", "priority: p1-high"]
assignees: ["@storyloomr/security-team"]

body:
    - type: markdown
      attributes:
          value: |
              ⚠️ **Security Notice**: If this is a critical security vulnerability, please consider reporting it privately to security@storyloomr.com instead of creating a public issue.

    - type: dropdown
      id: area
      attributes:
          label: Affected Area
          description: Which component or service is affected?
          options:
              - Authentication
              - API Gateway
              - Frontend (Web)
              - Mobile (iOS/Android)
              - Content Management
              - Media Processing
              - Infrastructure
              - Observability
              - Other
      validations:
          required: true

    - type: dropdown
      id: severity
      attributes:
          label: Severity
          description: How severe is this security issue?
          options:
              - Critical (Immediate action required)
              - High (Important security concern)
              - Medium (Moderate security risk)
              - Low (Minor security improvement)
          default: 0
      validations:
          required: true

    - type: textarea
      id: description
      attributes:
          label: Security Issue Description
          description: Describe the security vulnerability or concern
          placeholder: Please provide a clear description of the security issue...
      validations:
          required: true

    - type: textarea
      id: impact
      attributes:
          label: Potential Impact
          description: What could an attacker potentially do?
          placeholder: Describe the potential impact of this vulnerability...
      validations:
          required: true

    - type: textarea
      id: reproduction
      attributes:
          label: Reproduction Steps
          description: How can this vulnerability be reproduced? (Be careful not to include exploits)
          placeholder: |
              1. Step 1...
              2. Step 2...
              3. Observe security issue...
      validations:
          required: false

    - type: textarea
      id: mitigation
      attributes:
          label: Suggested Mitigation
          description: Do you have suggestions for fixing this issue?
          placeholder: Describe potential solutions or mitigations...
      validations:
          required: false

    - type: checkboxes
      id: disclosure
      attributes:
          label: Responsible Disclosure
          description: Security disclosure agreement
          options:
              - label: I understand this issue will be handled according to responsible disclosure practices
                required: true
              - label: I have not shared details of this vulnerability publicly
                required: true
