name: Auto-add to Project

on:
    issues:
        types: [opened]
    pull_request:
        types: [opened]

permissions:
    contents: read
    issues: write
    pull-requests: write
    repository-projects: write

jobs:
    add-to-project:
        name: Add issue/PR to organization project
        runs-on: ubuntu-latest

        steps:
            - name: Add to Organization Project
              uses: actions/add-to-project@v0.5.0
              with:
                  # Replace with your actual project URL
                  project-url: https://github.com/orgs/storyloomr/projects/1
                  github-token: ${{ secrets.BOT_TOKEN }}

            - name: Add comment for urgent items
              if: ${{ contains(github.event.issue.labels.*.name, 'priority') && contains(github.event.issue.labels.*.name, 'p0-urgent') }}
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.BOT_TOKEN }}
                  script: |
                      const issue_number = context.issue.number;
                      const repo = context.repo;

                      await github.rest.issues.createComment({
                        ...repo,
                        issue_number: issue_number,
                        body: '🚨 **URGENT**: This item has been marked as P0-urgent and added to the project board for immediate attention.'
                      });
